# Generated by Django 3.1.3 on 2020-11-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0002_auto_20201120_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='name',
        ),
    ]
